let shoe = [    
{ value: 1, name: '1H', suit: 'Hearts' },
{ value: 2, name: '2H', suit: 'Hearts' },
{ value: 3, name: '3H', suit: 'Hearts' },
{ value: 4, name: '4H', suit: 'Hearts' },
{ value: 5, name: '5H', suit: 'Hearts' },
{ value: 6, name: '6H', suit: 'Hearts' },
{ value: 7, name: '7H', suit: 'Hearts' },
{ value: 8, name: '8H', suit: 'Hearts' },
{ value: 9, name: '9H', suit: 'Hearts' },
{ value: 0, name: '10H', suit: 'Hearts' },
{ value: 0, name: 'JH', suit: 'Hearts' },
{ value: 0, name: 'QH', suit: 'Hearts' },
{ value: 0, name: 'KH', suit: 'Hearts' },
{ value: 1, name: '1D', suit: 'Diamonds' },
{ value: 2, name: '2D', suit: 'Diamonds' },
{ value: 3, name: '3D', suit: 'Diamonds' },
{ value: 4, name: '4D', suit: 'Diamonds' },
{ value: 5, name: '5D', suit: 'Diamonds' },
{ value: 6, name: '6D', suit: 'Diamonds' },
{ value: 7, name: '7D', suit: 'Diamonds' },
{ value: 8, name: '8D', suit: 'Diamonds' },
{ value: 9, name: '9D', suit: 'Diamonds' },
{ value: 0, name: '10D', suit: 'Diamonds' },
{ value: 0, name: 'JD', suit: 'Diamonds' },
{ value: 0, name: 'QD', suit: 'Diamonds' },
{ value: 0, name: 'KD', suit: 'Diamonds' },
{ value: 1, name: '1S', suit: 'Spades' },
{ value: 2, name: '2S', suit: 'Spades' },
{ value: 3, name: '3S', suit: 'Spades' },
{ value: 4, name: '4S', suit: 'Spades' },
{ value: 5, name: '5S', suit: 'Spades' },
{ value: 6, name: '6S', suit: 'Spades' },
{ value: 7, name: '7S', suit: 'Spades' },
{ value: 8, name: '8S', suit: 'Spades' },
{ value: 9, name: '9S', suit: 'Spades' },
{ value: 0, name: '10S', suit: 'Spades' },
{ value: 0, name: 'JS', suit: 'Spades' },
{ value: 0, name: 'QS', suit: 'Spades' },
{ value: 0, name: 'KS', suit: 'Spades' },
{ value: 1, name: '1X', suit: 'Clubs' },
{ value: 2, name: '2C', suit: 'Clubs'},
{ value: 3, name: '3C', suit: 'Clubs' },
{ value: 4, name: '4C', suit: 'Clubs'},
{ value: 5, name: '5C', suit: 'Clubs' },
{ value: 6, name: '6C', suit: 'Clubs' },
{ value: 7, name: '7C', suit: 'Clubs' },
{ value: 8, name: '8C', suit: 'Clubs' },
{ value: 9, name: '9C', suit: 'Clubs' },
{ value: 0, name: '10C', suit: 'Clubs' },
{ value: 0, name: 'JC', suit: 'Clubs' },
{ value: 0, name: 'QC', suit: 'Clubs' },
{ value: 0, name: 'KC', suit: 'Clubs' }
]

